### ISSUE TITLE
Shouldn't actions and reducers live under root?

### ISSUE THREAD

**Issue by adi-works** [dashukin/react-redux-template#1]
I'm trying to figure out the re-usability of your approach.

**Comment by dashukin** [comment]
Hi @adi518 
Each container (smart component) is responsible for its piece of state so it is expected to have its own reducers and actions.
In case there should be some common data shared across all components - appropriate constants/actions/sagas/reducers are expected to be created under the /data/FeatureName folder in the same way like containers do. 
Keeping all component related constants/actions/sagas/reducers in on place with their view component makes it possible to create/edit/move/remove such feature grouped components with the only efforts of creating small modifications to the parent imports.
In case some feature component (lets name it FeatureChildOne) is only expected to be a part of Feature component - it should be nested inside it and could be only used by Feature component. But as long as such component should be reused all acros the application - it's exepcted to be located inside /components/FeatureChild path with appropriate naming.
